### ISSUE TITLE
Cover Art won't load for next music tracks in a playlist

### ISSUE THREAD

**Issue by doom-hamster** [harryberlin/script.reliableresume#1]
Steps to reproduce:
1) Have a saved playlist in the addon
2) Exit & relaunch Kodi
3) Start the addon ReliableResume, track starts playing in the background.
4) Open Fullscreen view for the Music Player, Cover Art loads for the current track.
5) Switch to the next track - Cover Art is empty, same for every next track.

I have Kodi v19.5 installed on Android TV 11, playing mp3 files through SMB share. Installed addon named "script.reliableresume-latest.zip".

If after the 3rd step i open Music Playlist first, and only then go into Fullscreen - then Cover Art loads successfully for next tracks. I would like to have a toggleable option in the addon: "Open music playlist after addon start", as a simple QoL improvement - if fixing the base issue is complicated.

**Comment by harryberlin** [comment]
you have seen the setting autostart?

**Comment by doom-hamster** [comment]
> you have seen the setting autostart?

Indeed, enabling it just makes the addon run when Kodi launches, audio loads and starts playing in background, and the issue still happens if i to open the music in fullscreen.

**Comment by harryberlin** [comment]
the addon loads playlist only.
how do you load the Playlist by yourself, after failure loading?
do you have an Idea how to fix?

**Comment by doom-hamster** [comment]
> the addon loads playlist only.
> how do you load the Playlist by yourself, after failure loading?
> do you have an Idea how to fix?

I don't understand your question, or maybe you don't understand the problem i have. 

The problem is that the Album Artwork (Cover Art) which is embedded in music files - it just doesn't show itself on any next track in the playlist, that the addon restored. The addon works, it successfully loads previously played playlist (after Kodi reboot for example), issue is only about the Artwork, after i switch to Fullscreen View of the music player.

> do you have an Idea how to fix?

I think a partial-fix would be automatically opening Playlist View: ![изображение](https://user-images.githubusercontent.com/106200718/224562919-ec371d9c-780b-49a4-ab4c-a7e0882942fd.png)
, right after the addon launch. That way, the Artwork starts loading for next tracks. Thats what i meant - after addon restores the old playlist, i open Playlist View first, then Fullscreen view - and that makes the Cover Art visible for all next tracks.

**Comment by harryberlin** [comment]
are you sure it's an issue of the addon? may it's an issue of kodi?

**Comment by doom-hamster** [comment]
> are you sure it's an issue of the addon? may it's an issue of kodi?

Yes. I couldn't reproduce this issue in any way without using the addon. 

Cover Art for next tracks always loads, if i start music playback with normal means: Home -> [Music](https://kodi.wiki/view/Music_navigation#General_Navigation) and opening tracks in folders, or m3u playlists. I select a track / playlist, music starts playing, i can open Fullscreen view right away and Cover Art loads for next tracks without fault.

**Comment by harryberlin** [comment]
try latest commit.
i think it's a kodi issue. by loading to video playlist and start playing this, it is working.
only audio playlist has the issue.
becaue
if you load a playlist by usual way, you will get a meta-info dialog, which processes the load of meta info. by loading with addon, there is no dialog.

**Comment by doom-hamster** [comment]
Ok, i tested the latest commit 3c7dab1.

It fixed existing issue, all next tracks in the playlist now show their Cover Art, when in Fullscreen view.

However, it added more issues.
"Next" track info is now empty:

![Screenshot_20230313-133329](https://user-images.githubusercontent.com/106200718/224655059-75017860-db03-40c3-93e1-e5db67f0c4d9.jpg)

How it should be (if i manually select to play a track in my m3u playlist):
![Screenshot_20230313-133500](https://user-images.githubusercontent.com/106200718/224655134-c23d0486-95dc-4d91-9833-c3ef67d765fa.jpg)

Another issue is that Music Playlist doesn't highlight the track that is now playing, and doesn't focus on it:

![Screenshot_20230313-133544](https://user-images.githubusercontent.com/106200718/224656087-04898641-995a-4170-bc91-6b08ddf1ae63.jpg)
![Screenshot_20230313-133605](https://user-images.githubusercontent.com/106200718/224656114-e0afcbfc-28dc-4eb6-b81a-2fc68bbddf5b.jpg)

How it should be (if i manually select to play a track in my m3u playlist):
![Screenshot_20230313-133655](https://user-images.githubusercontent.com/106200718/224656164-349a0695-bd27-4408-b8ff-9f8e34d9fb72.jpg)


What's interesting, using addon with latest commit, the addon after starting switches Kodi to Fullscreen Music view instantly - is it intended?

**Comment by harryberlin** [comment]
please edit code to playerid 0 and try again.

**Comment by doom-hamster** [comment]
> please edit code to playerid 0 and try again.

I suppose you meant this line in default.py:
xbmc.Player().play(item=xbmc.PlayList(1), windowed=False, startpos=self.plpos)

I've changed PlayList(1) to PlayList(0). Reinstalled addon, and now its working the same way, as when i've opened this Issue thread.

Also tried latest commit 69eefa3 - same thing.

I'm afraid i can't help with code. But i can suggest an idea for workaround fix: you can make it so when Music is resumed with the addon, automatically and instantly open [Playlist View](https://user-images.githubusercontent.com/106200718/224562919-ec371d9c-780b-49a4-ab4c-a7e0882942fd.png). The opening of Playlist View makes Metadata load correctly for next tracks, including Cover Art.

**Comment by harryberlin** [comment]
First of all: It's a Kodi issue. Please open an issue at kodi git.

Feel free to add PR for workaround this "issue" in the addon.

**Comment by doom-hamster** [comment]
> First of all: It's a Kodi issue. Please open an issue at kodi git.

Why it is an issue within Kodi, if the problem arises only when using this addon?

The workaround i'm suggesting i already can do by modding the skin, by using a custom xml like this:

```
<?xml version="1.0" encoding="utf-8"?>
<window type="dialog" id="1112">
    <allowoverlay>no</allowoverlay>
	<onload `condition="!Window.IsActive(visualisation)">ActivateWindow(MusicPlaylist)</onload>`
	<visible>Integer.IsEqual(MusicPlayer.Time(secs),1)</visible>
    <controls></controls>
</window>
```

Its a bit of a rough way to do this, but its good enough for me. I just thought to contribute to bettering the addon for everyone who might use it. But thanks anyway, for the work you've already done on the addon.

**Comment by harryberlin** [comment]
it's a kodi issue, because the addon uses kodi python functions to load the playlist.

your code is just skin code. will not run as python script.

do you have tested an other resume addon without this issue?
